<a href="https://colab.research.google.com/github/poietes5150/SuperCoding/blob/main/pytorch_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(f"PyTorch 버전: {torch.__version__}")
print(f"CUDA 사용 가능 여부: {torch.cuda.is_available()}")

PyTorch 버전: 2.6.0+cu124
CUDA 사용 가능 여부: True


# **3. Tensor 생성**

Tensor는 PyTorch의 기본 데이터 구조입니다. 아래는 다양한 방법으로 텐서를 생성하는 예시입니다.

In [ ]:
from os import X_OK
import torch
import numpy as np

# 리스트로부터 생성
data = [[1,2], [3,4]]
x_data = torch.tensor(data)
print(f"원본 데이터로부터 생성:\n {x_data}")
print(f"\tndim: {x_data.ndim}")
print(f"\tshape: {x_data.shape}")
print(f"\tsize: {x_data.size()}")

# NumPy (ndarray) 배열로부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"NumPy 배열로부터 생성:\n {x_np}")

# 다른 텐서와 동일한 형태로 생성
X_ones = torch.ones_like(x_data)      # 1로 채움
print(f"1로 채운 텐서:\n {X_ones}")

# 0~1 사이 랜덤
X_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"랜덤 텐서:\n {X_rand}")

# float로 변환
x_int = np.arange(10).reshape(5,2)
x_float = torch.FloatTensor(x_int)
print(f"float 텐선:\n {x_float}")

원본 데이터로부터 생성:
 tensor([[1, 2],
        [3, 4]])
	ndim: 2
	shape: torch.Size([2, 2])
	size: torch.Size([2, 2])
NumPy 배열로부터 생성:
 tensor([[1, 2],
        [3, 4]])
1로 채운 텐서:
 tensor([[1, 1],
        [1, 1]])
랜덤 텐서:
 tensor([[0.5157, 0.4292],
        [0.5148, 0.5970]])
float 텐선:
 tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])


In [ ]:
# 현재 개발 환경에서 cuda 사용이 가능한 경우, tensor 를 cuda 버전으로 변경
x_data.device

device(type='cpu')

In [ ]:
# 현재 개발 환경에서 cuda 사용이 가능한 경우, tensor 를 cuda 버전으로 변경
print(x_data.device)

if torch.cuda.is_available():
    # x_data_cuda = x_data.cuda()
    x_data_cuda = x_data.to("cuda")
x_data_cuda.device
print(x_data_cuda.device)

cpu
cuda:0


# **Tensor와 NumPy 간 변환**

In [ ]:
from os import X_OK
import torch
import numpy as np

# 텐서를 NumPyㄹ 배열로 변환
tensor = torch.ones(3,3)
print(f"텐서:\n {tensor}")
np_tensor = tensor.numpy()
print(f"텐서를 넘파이 배열러 변환:\n {np_tensor}, {type(np_tensor)}")

# NumPy 배열을 텐서로 변환
tensor_from_np = torch.from_numpy(np_tensor)
print(f"넘파이 배열을 텐서로 변환:\n {tensor_from_np}, {type(tensor_from_np)}")

텐서:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
텐서를 넘파이 배열러 변환:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], <class 'numpy.ndarray'>
넘파이 배열을 텐서로 변환:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]), <class 'torch.Tensor'>


# **NumPy와 유사한 operations**

In [ ]:
import numpy as np
import torch

data = [[4,5,6],[50,20,10],[-2,8,22]]
x_data = torch.tensor(data)
print(x_data)

tensor([[ 4,  5,  6],
        [50, 20, 10],
        [-2,  8, 22]])


In [ ]:
# tensor를 인덱싱
x_data[1:]

tensor([[50, 20, 10],
        [-2,  8, 22]])

In [ ]:
x_data[:2, 1:]

tensor([[ 5,  6],
        [20, 10]])

In [ ]:
x_data_np = x_data.numpy()
x_data_np[:2, 1:]

array([[ 5,  6],
       [20, 10]])

In [ ]:
# tensor를 1차원의 vector로
x_data.flatten()

tensor([ 4,  5,  6, 50, 20, 10, -2,  8, 22])

In [ ]:
# x_data shape과 동일한 크기로 원소 1을 같는 tensor 생성
torch.ones_like(x_data)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

# **4. Tensor 속성과 연산**

In [ ]:
import numpy as np
import torch

tensor = torch.rand(3,4)
print(f"ndim (차원): {tensor.ndim}")
print(f"size (크기): {tensor.size()}")
print(f"shape (모양): {tensor.shape}")
print(f"dtype (자료형): {tensor.dtype}")
print(f"device (장치): {tensor.device}")

ndim (차원): 2
size (크기): torch.Size([3, 4])
shape (모양): torch.Size([3, 4])
dtype (자료형): torch.float32
device (장치): cpu


# 텐서 조작 예시



*   view() = contigous (연속 메모리) 필요, 일반적으로 복사 안함, 속도 빠름, 오류 발생 가능
*   reshape() - 연속메모리 필요 없음 (메모리 자동처리), 필요시 복사, 메모리 자동처리 되므로 오류 적음, 복사 발생시 느릴 수 있음



In [ ]:
# 인자로 받은 size의 random tensor를 생성
tensor_ex = torch.rand(size=(2,3,2))
print(tensor_ex)

# tensor가 contigous한 경우, 인자로 받은 사이즈에 맞춰 tensor의 사이즈를 변경
# contigous (연속 메모리) 필요, 일반적으로 복사 안함, 속도 빠름, 오류 발생 가능
tensor_ex.view([-1, 6])

tensor([[[0.7261, 0.5943],
         [0.6313, 0.4893],
         [0.1472, 0.1933]],

        [[0.2466, 0.1100],
         [0.6276, 0.9524],
         [0.2300, 0.0473]]])


tensor([[0.7261, 0.5943, 0.6313, 0.4893, 0.1472, 0.1933],
        [0.2466, 0.1100, 0.6276, 0.9524, 0.2300, 0.0473]])

In [ ]:
# tensor의 contigous 상태에 관계없이, tensor의 사이즈를 변경
# 연속메모리 필요 없음 (메모리 자동처리), 필요시 복사, 메모리 자동처리 되므로 오류 적음, 복사 발생시 느릴 수 있음
tensor_ex.reshape([-1, 6])

tensor([[0.7261, 0.5943, 0.6313, 0.4893, 0.1472, 0.1933],
        [0.2466, 0.1100, 0.6276, 0.9524, 0.2300, 0.0473]])

In [ ]:
import torch

# 1. 원본 텐서 생성
x = torch.randn(2, 3)
print(f"원본 x:\n{x}")
# 2. 전치(transpose) -> 메모리가 연속되지 않음
x_t = x.t()   # shape: (3,2)
print(f"\n전치 x_t:\n{x_t}")
# 3. view 시도 -> 실패(RuntimeError 발생)
try:
  x_view = x_t.view(6)
except RuntimeError as e:
  print(f"\n.view() 에러 발생: {e}")
# 4. reshape 시도 -> 성공 (필요하면 복사)
x_reshape = x_t.reshape(6)
print(f"\n.reshape() 성공:\n {x_reshape}")

원본 x:
tensor([[-1.7167,  0.5024,  0.6261],
        [-0.9967, -0.0513,  2.0880]])

전치 x_t:
tensor([[-1.7167, -0.9967],
        [ 0.5024, -0.0513],
        [ 0.6261,  2.0880]])

.view() 에러 발생: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

.reshape() 성공:
 tensor([-1.7167, -0.9967,  0.5024, -0.0513,  0.6261,  2.0880])


In [ ]:
# 원소 0을 같는 tensor를 생성하고, 사이즈를 변경 후, 값을 변경
# view와 reshape 메서드 간 a, b의 값을 확인해보자
# 메모리가 복사를 안했으므로 b도 같이 변함
a = torch.zeros(3,2)
b = a.view(6)
a.fill_(1)

print(f"a:\n {a}")
print(f"b:\n {b}")

a:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
b:
 tensor([1., 1., 1., 1., 1., 1.])


In [ ]:
# 원소 0을 같는 tensor를 생성하고, 사이즈를 변경 후, 값을 변경
# 메모리가 복사되었으므로 b는 안 변함
a = torch.zeros(3,2)
b = a.t().reshape(6)
a.fill_(1)

print(f"a:\n {a}")
print(f"b:\n {b}")

a:
 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
b:
 tensor([0., 0., 0., 0., 0., 0.])




*   squeez(), unsqueeze()



In [ ]:
# 텐서를 생성한 후, 크기 1의 차원을 같는 dimension을 squeeze
# size = (1) => 열
# size = (1,2) => 행, 열
# size = (2,1,2) => 깊이, 행, 열
# 앞으로 하나씩 붙는다 => axis
tensor_ex = torch.rand(size=(2,1,2))
print(tensor_ex)
print(tensor_ex.shape)

tensor_ex_squeezed = tensor_ex.squeeze()
print(tensor_ex_squeezed)
print(tensor_ex_squeezed.shape)

tensor([[[0.6423, 0.7641]],

        [[0.2334, 0.9937]]])
torch.Size([2, 1, 2])
tensor([[0.6423, 0.7641],
        [0.2334, 0.9937]])
torch.Size([2, 2])


In [ ]:
# 새로운 차원에 축을 생성
tensor_ex = torch.rand(size=(2,2))
print(tensor_ex)
print(tensor_ex.unsqueeze(0).shape)
print(tensor_ex.unsqueeze(0))
print(tensor_ex.unsqueeze(1).shape)
print(tensor_ex.unsqueeze(1))
print(tensor_ex.unsqueeze(2).shape)
print(tensor_ex.unsqueeze(2))

tensor([[0.1668, 0.1248],
        [0.7293, 0.5722]])
torch.Size([1, 2, 2])
tensor([[[0.1668, 0.1248],
         [0.7293, 0.5722]]])
torch.Size([2, 1, 2])
tensor([[[0.1668, 0.1248]],

        [[0.7293, 0.5722]]])
torch.Size([2, 2, 1])
tensor([[[0.1668],
         [0.1248]],

        [[0.7293],
         [0.5722]]])


In [ ]:
test1 = torch.ones(2,1,2)
print(test1)
test2 = torch.ones(size=(2,3))
print(test2)
test3 = torch.ones(size=(2,1,2))
print(test3)

tensor([[[1., 1.]],

        [[1., 1.]]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[[1., 1.]],

        [[1., 1.]]])


# 텐서 연산 예시

In [ ]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[10,20],[30,40]])
c = torch.tensor([1,2,3])
d = torch.tensor([4,5,6])

print(f"덧셈: \n {a+b}")
print(f"요소별(성분) 곱셈: \n {a*b}")
print(f"행렬곱(matmul): \n {torch.matmul(a, b)}")
print(f"행렬곱(mm, 2D): \n {torch.mm(a, b)}") # 행렬곱 2D 에서만 가능
print(f"행렬곱(dot, 1D): \n {torch.dot(c, d)}") # 행렬곱 1D 에서만 가능

덧셈: 
 tensor([[11, 22],
        [33, 44]])
요소별(성분) 곱셈: 
 tensor([[ 10,  40],
        [ 90, 160]])
행렬곱(matmul): 
 tensor([[ 70, 100],
        [150, 220]])
행렬곱(mm, 2D): 
 tensor([[ 70, 100],
        [150, 220]])
행렬곱(dot, 2D): 
 32


In [ ]:
# broad casting
print(a+10)

tensor([[11, 12],
        [13, 14]])


In [ ]:
# broad casting이 지원되어 행렬 곱 연산이 가능
a = torch.rand(5,2,3)
print(a.shape)
b = torch.rand(3,4)
print(b.shape)
a.matmul(b).shape

# b가 5번 복제된 것 처럼 동작

torch.Size([5, 2, 3])
torch.Size([3, 4])


torch.Size([5, 2, 4])

In [ ]:
A = torch.tensor([[1,2],[3,4],[5,6]]) # shape: (3, 2)
b = torch.tensor([1,0])               # shape: (2,)

# (3, 2) @ (2,) -> (3,) 결과: 각행 벡터와 b의 내적
print(A)
print(b)
out = torch.matmul(A, b)  # broadcasting
print(out)  # tensor([ 5, 11, 17 ])

tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([1, 0])
tensor([1, 3, 5])


# **5. CUDA(GPU) 사용하기**

In [ ]:
import torch
import numpy as np

tensor = torch.rand(3, 4)
print(f"현재 사용중인 장치: {tensor.device}")

# 현재 개발 환경에서 cuda 사용이 가능한 경우, tensor를 cuda 버전으로 변경
if torch.cuda.is_available():
  tensor_cuda = tensor.to('cuda')
  print(f"GPU로 이동한 텐서:\n{tensor_cuda}")

# 다시 CPU로 이동
tensor_cpu = tensor.to("cpu")
print(f"다시 CPU로 이동한 텐서:\n{tensor_cpu}")

현재 사용중인 장치: cpu
GPU로 이동한 텐서:
tensor([[0.3733, 0.8158, 0.3282, 0.1865],
        [0.6482, 0.7045, 0.2159, 0.0085],
        [0.7170, 0.7988, 0.3959, 0.6191]], device='cuda:0')
다시 CPU로 이동한 텐서:
tensor([[0.3733, 0.8158, 0.3282, 0.1865],
        [0.6482, 0.7045, 0.2159, 0.0085],
        [0.7170, 0.7988, 0.3959, 0.6191]])


# 머신러닝/딥러닝을 위한 tensor 연산

In [ ]:
import numpy as np
import torch

tensor = torch.FloatTensor([0.6, 0.2, 0.1])
# 생성한 tensor에서 softmax 함수를 계산
h_tensor = torch.nn.functional.softmax(tensor, dim=0)
print(h_tensor)

tensor([0.4392, 0.2944, 0.2664])


In [ ]:
import numpy as np
import torch
import torch.nn.functional as F # 이런식으로 많이 사용

tensor = torch.FloatTensor([0.6, 0.2, 0.1])
# 생성한 tensor에서 softmax 함수를 계산
h_tensor = F.softmax(tensor, dim=0)
print(h_tensor)

tensor([0.4392, 0.2944, 0.2664])


In [ ]:
# 예제 텐서 (10행 5열)
y = torch.randint(5, (10, 5))
print(f"y:\n{y}")

# 각 행의 argmax (최대값의 인덱스)
y_label = y.argmax(dim=1)
print(f"argmax indices:\n{y_label}")

# 최대값 자체를 구하려면
y_max = y.max(dim=1)
print(f"max values:\n{y_max}")

# y_label 이용하는 방법 1: torch.gather 사용 (추천!)
y_max = torch.gather(y, 1, y_label.unsqueeze(1)).squeeze(1)
print(f"max values:\n{y_max}")

# y_label 방법 2: python 리스트 스타일 (느림!)
y_max = torch.tensor([row[idx] for row, idx in zip(y, y_label)])
print(f"max values:\n{y_max}")

y:
tensor([[1, 4, 2, 1, 2],
        [1, 1, 0, 2, 0],
        [3, 0, 4, 1, 2],
        [2, 4, 0, 4, 3],
        [4, 2, 1, 4, 3],
        [3, 0, 3, 2, 1],
        [2, 0, 1, 1, 0],
        [2, 3, 1, 1, 2],
        [0, 4, 4, 3, 2],
        [4, 0, 1, 1, 0]])
argmax indices:
tensor([1, 3, 2, 1, 0, 0, 0, 1, 1, 0])
max values:
torch.return_types.max(
values=tensor([4, 2, 4, 4, 4, 3, 2, 3, 4, 4]),
indices=tensor([1, 3, 2, 1, 0, 0, 0, 1, 1, 0]))
max values:
tensor([4, 2, 4, 4, 4, 3, 2, 3, 4, 4])
max values:
tensor([4, 2, 4, 4, 4, 3, 2, 3, 4, 4])


In [ ]:
# one-hot 인코딩으로 변환합니다.
torch.nn.functional.one_hot(y_label)

tensor([[0, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0]])

In [ ]:
import itertools

# cartesian product를 수행합니다.
a = [1, 2, 3]
b = [10, 20]
list(itertools.product(a, b))

[(1, 10), (1, 20), (2, 10), (2, 20), (3, 10), (3, 20)]

In [ ]:
# PyTorch 에서 지원하는 메서드를 통해 cartesian product를 수행합니다.
a = [1, 2, 3]
b = [10, 20]

tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
torch.cartesian_prod(tensor_a, tensor_b)

tensor([[ 1, 10],
        [ 1, 20],
        [ 2, 10],
        [ 2, 20],
        [ 3, 10],
        [ 3, 20]])

# 연습 문제 & 정답

**Q1.** shape이 (3,3)이고 값이 모두 7인 텐서를 만들어 보세요.

**Q2.** 랜덤 텐서 두 개를 생성하고 덧셈과 곱셈 결과를 출력해 보세요.

**Q3.** torch.matmul()을 이용해 2x3, 3x2 행렬의 곱을 계산해 보세요.

**Q4.** 아래와 같이 텐서를 생성하고 CUDA를 지원하면 GPU로 이동해 보세요.



```
tensor = torch.rand(3, 4)
tensor = tensor.to("cpu")
print(f"현재 device: {tensor.device}")
```



In [ ]:
# Q1. shape이 (3,3)이고 값이 모두 7인 텐서를 만들어 보세요.
tensor_q1 = torch.full((3, 3), 7)
print(tensor_q1)

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])


In [ ]:
# Q2. 랜덤 텐서 두 개를 생성하고 덧셈과 곱셈 결과를 출력해 보세요.
tensor_q2_1 = torch.rand(3, 4)
tensor_q2_2 = torch.rand(3, 4)
print(tensor_q2_1 * tensor_q2_2)

tensor([[0.2538, 0.3025, 0.0300, 0.0541],
        [0.4008, 0.0668, 0.0791, 0.3617],
        [0.0794, 0.1034, 0.0719, 0.1044]])


In [ ]:
# Q3. torch.matmul()을 이용해 2x3, 3x2 행렬의 곱을 계산해 보세요.
tensor_q3_1 = torch.rand(2, 3)
tensor_q3_2 = torch.rand(3, 2)
print(torch.matmul(tensor_q3_1, tensor_q3_2))

tensor([[0.9792, 0.3069],
        [1.4881, 0.4273]])


In [ ]:
# Q4. 아래와 같이 텐서를 생성하고 CUDA를 지원하면 GPU로 이동해 보세요.
tensor = torch.rand(3, 4)
tensor = tensor.to("cpu")
print(f"현재 device: {tensor.device}")

if torch.cuda.is_available():
  tensor = tensor.to("cuda")
  print(f"현재 device: {tensor.device}")


현재 device: cpu
현재 device: cuda:0
